### ISSUE TITLE
How to select the best result?

### ISSUE THREAD

**Issue by h-somehow** [Huntersxsx/MGPN#2]
Hi! Thanks for your work first.
I am wondering how to select the best result during training. Is the best result chosen based on the sum of all Rank@n,mIoU@m results, or one special metric(e.g. mIoU)?

**Comment by Huntersxsx** [comment]
- In our code, we have set torch.backends.cudnn.deterministic = False and cudnn.benchmark = True. Due to this configuration, the best results obtained during training may vary.

- Regarding the selection of checkpoints, we prefer to prioritize the reported performance based on the mIoU metric. However, you are welcome to consider other metrics as well when choosing a checkpoint. Sometimes, a checkpoint may exhibit higher R@1 performance but lower R@5 performance. Therefore, it is unnecessary to rely solely on a single metric for checkpoint selection. Nonetheless, it is important to ensure that the reported performance across all metrics is evaluated using the same chosen checkpoint.
